on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        run_id: ${{ github.event.workflow_run.id }}
        github_token: ${{secrets.GITHUB_TOKEN}}
        repo: ${{ github.repository }}
        check_artifacts: false
        branch: master
